### ISSUE TITLE
web.baseURL configuration parameter is not applied

### ISSUE THREAD

**Issue by mrtamm** [GenomicDataInfrastructure/starter-kit-lsaai-mock#9]
Documentation about **application.properties** says following:

```
### URL where the application runs
main.oidc.issuer.url=http://localhost:8080/oidc/
### base path for web (e.g. issuer without trailing slash)
web.baseURL=https://localhost:8080/oidc
```

However, problems appear when I change these parameters like:

```
main.oidc.issuer.url=http://lsaai:8080/oidc/
web.baseURL=http://localhost:8000/oidc
```

### Problem 1

When I open the URL http://localhost:8000/oidc/, I see that the web page fails to load its resources because the HTML `<head>` block contains

```
<base href="http://lsaai:8080/oidc/">
```

Therefore, the page still uses the value of `main.oidc.issuer.url` and not `web.baseURL`.

Notice that in the parameters I also have **different port numbers**! So the problem is not just about mapping docker container host to localhost. I also need to define a different port number. So the parameter `web.baseURL` seems the most appropriate way to do this. On the other hand, the web page might also work if it would not use the `<base>` element at all.

### Problem 2

When I visit http://localhost:8000/oidc/.well-known/openid-configuration I see:

```
"authorization_endpoint": "http://lsaai:8080/oidc/authorize",
```

However, it should apply the `web.baseURL` parameter here because currently it fails to redirect the user to the right authority (host and port).

---

For background info, this is a snippet from my **docker-compose.yml** for the lsaai-mock service:

```yaml
services:
  lsaai:
    container_name: lsaai
    image: registry.gitlab.ics.muni.cz:443/perun/deployment/proxyidp/proxyidp-public-docker-images/ls_aai_mock:2.5.2-broker2.1.10-tomcat9.0-jdk11
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ../config/lsaai/:/etc/lsaai-mock:ro
```
